config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/index'
  # get 'welcome/home', to:"welcome#home"
  #get 'welcome/about', to:"welcome#about"
    root 'welcome#home'
    get 'about', to:"welcome#about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>About page </h1>
<%= link_to "HOME" ,root_path %>
<%= image_tag 'images1.jpeg' %>

app/views/welcome/home.html.erb
<h1> welcome in home</h1>
<%=link_to 'About' ,about_path %>

app/views/welcome/index.html.erb
<h1>Welcome To my web page</h1>
<img src="images/images1.jpeg"></img>
<h1>Hello, Rails!</h1>
<p>Find me in app/views/welcome/index.html.erb</p>